FROM rust:1.63 as builder
WORKDIR /usr/src

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y musl-tools && \
	apt-get install -y libssl-dev && \
	apt-get install -y sqlite3 && \
	apt-get install -y pkg-config && \
    rustup target add x86_64-unknown-linux-musl

RUN USER=root cargo new eddie-bot
WORKDIR /usr/src/eddie-bot
COPY Cargo.toml Cargo.lock ./
COPY bot_utils ./bot_utils
RUN cargo install --target x86_64-unknown-linux-musl --path .

COPY src ./src
RUN cargo install --target x86_64-unknown-linux-musl --offline --path .


FROM scratch
COPY --from=builder /usr/local/cargo/bin/eddie-bot .
COPY config.json ./
COPY blacklist.txt ./
COPY input.json ./
COPY storage.db ./storage.db
CMD ["./eddie-bot"]
